name: klu
version: 0.2.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A sparse LU factorization algorithm suited to circuit simulation.
homepage: http://www.cise.ufl.edu/research/sparse/klu/
dependencies:
  amd: any
  btf: any
  colamd: any
  csparse: any
  unittest: '>=0.11.0+3 <0.12.0'
